import { Medicine, Store } from "./types";
import metforminImg from "./src/assets/medicines/Diabetes/Metformin.png";
import gliclazideTabletImg from "./src/assets/medicines/Diabetes/gliclazide-tablet.png";
import steglatroImg from "./src/assets/medicines/Diabetes/Steglatro-15mg.png";
import tenezamImg from "./src/assets/medicines/Diabetes/Teneza-M.png";

import aspirinImg from "./src/assets/medicines/heart/Aspirin.jpg";
import atorvastatinImg from "./src/assets/medicines/heart/atorvastatin.png";
import cardiacImg from "./src/assets/medicines/heart/cardiac-medicines.png";
import furosemideImg from "./src/assets/medicines/heart/Furosemide.png";
import lisinoprilImg from "./src/assets/medicines/heart/Lisinopril.png";
import metoprololImg from "./src/assets/medicines/heart/metoprolol-100-mg.png";

import citicolineImg from "./src/assets/medicines/Neurology/Citicoline&Piracetam.jpg";
import clonazepamImg from "./src/assets/medicines/Neurology/Clonazepam-MD-Tablets.png";
import fluvoxamineImg from "./src/assets/medicines/Neurology/Fluvoxamine-Tablets-50mg.png";
import neuroImg from "./src/assets/medicines/Neurology/neuro-mpg-75.png";

import acetaminophenImg from "./src/assets/medicines/pain-relief/acetaminophen.png";
import codeineImg from "./src/assets/medicines/pain-relief/codeine.png";
import diclofenacImg from "./src/assets/medicines/pain-relief/diclofenac.jpg";
import ibuprofenImg from "./src/assets/medicines/pain-relief/ibuprofen.jpg";
import naproxenImg from "./src/assets/medicines/pain-relief/naproxen.jpeg";
import tramadolImg from "./src/assets/medicines/pain-relief/Tramadol.jpg";

import albuterolImg from "./src/assets/medicines/Respiratory/albuterol.jpg";
import budesonideImg from "./src/assets/medicines/Respiratory/budesonide.jpg";
import fluticasoneImg from "./src/assets/medicines/Respiratory/fluticasone propionate.jpg";
import montelukastImg from "./src/assets/medicines/Respiratory/montelukast.jpg";
import prednisoneImg from "./src/assets/medicines/Respiratory/prednisone.jpeg";

export const MOCK_MEDICINES: Medicine[] = [
  {
    id: 1,
    disease: "Diabetes",
    name: "Metformin",
    genericName: "Metformin Hydrochloride",
    manufacturer: "Cipla",
    category: "Diabetes",
    price: 80,
    stock: 70,
    discount: 0,
    finalPrice: 80,
    imageUrl: metforminImg,
    description: "Used to control high blood sugar in type 2 diabetes.",
  },
  {
    id: 2,
    disease: "Diabetes",
    name: "Gliclazide Tablet",
    genericName: "Gliclazide",
    manufacturer: "Dr Reddy's",
    category: "Diabetes",
    price: 95,
    stock: 40,
    discount: 0,
    finalPrice: 95,
    imageUrl: gliclazideTabletImg,
    description: "Helps lower blood sugar levels in patients with type 2 diabetes.",
  },
  {
    id: 3,
    disease: "Heart",
    name: "Aspirin",
    genericName: "Acetylsalicylic Acid",
    manufacturer: "Bayer",
    category: "Heart",
    price: 60,
    stock: 90,
    discount: 0,
    finalPrice: 60,
    imageUrl: aspirinImg,
    description: "Reduces pain, fever, and inflammation; also helps prevent heart attacks.",
  },
  {
    id: 4,
    disease: "Pain Relief",
    name: "Ibuprofen",
    genericName: "Ibuprofen",
    manufacturer: "Abbott",
    category: "Pain Relief",
    price: 75,
    stock: 75,
    discount: 0,
    finalPrice: 75,
    imageUrl: ibuprofenImg,
    description: "Non-steroidal anti-inflammatory drug (NSAID) for pain relief.",
  },
  {
    id: 5,
    disease: "Respiratory",
    name: "Montelukast",
    genericName: "Montelukast Sodium",
    manufacturer: "Lupin",
    category: "Respiratory",
    price: 160,
    stock: 40,
    discount: 0,
    finalPrice: 160,
    imageUrl: montelukastImg,
    description: "Used to prevent asthma attacks and treat allergies.",
  },
  {
    id: 6,
    disease: "Neurology",
    name: "Clonazepam",
    genericName: "Clonazepam",
    manufacturer: "Roche",
    category: "Neurology",
    price: 130,
    stock: 33,
    discount: 0,
    finalPrice: 130,
    imageUrl: clonazepamImg,
    description: "Used to prevent and control seizures and panic attacks.",
  },
  {
    id: 7,
    disease: "Diabetes",
    name: "Steglatro",
    genericName: "Ertugliflozin",
    manufacturer: "MSD",
    category: "Diabetes",
    price: 450,
    stock: 25,
    discount: 5,
    finalPrice: 427.5,
    imageUrl: steglatroImg,
    description: "Sodium-glucose co-transporter 2 (SGLT2) inhibitor for type 2 diabetes.",
  },
  {
    id: 8,
    disease: "Diabetes",
    name: "Teneza-M",
    genericName: "Teneligliptin + Metformin",
    manufacturer: "Glenmark",
    category: "Diabetes",
    price: 120,
    stock: 55,
    discount: 0,
    finalPrice: 120,
    imageUrl: tenezamImg,
    description: "Combination therapy for managing high glycemic levels.",
  },

  // --- HEART ---
  {
    id: 9,
    disease: "Heart",
    name: "Atorvastatin",
    genericName: "Atorvastatin Calcium",
    manufacturer: "Pfizer",
    category: "Heart",
    price: 110,
    stock: 100,
    discount: 10,
    finalPrice: 99,
    imageUrl: atorvastatinImg,
    description: "Statin medication used to prevent cardiovascular disease and treat abnormal lipid levels.",
  },
  {
    id: 10,
    disease: "Heart",
    name: "Furosemide",
    genericName: "Furosemide",
    manufacturer: "Sanofi",
    category: "Heart",
    price: 45,
    stock: 120,
    discount: 0,
    finalPrice: 45,
    imageUrl: furosemideImg,
    description: "Loop diuretic used to treat fluid build-up due to heart failure or kidney disease.",
  },
  {
    id: 11,
    disease: "Heart",
    name: "Lisinopril",
    genericName: "Lisinopril",
    manufacturer: "Zydus",
    category: "Heart",
    price: 85,
    stock: 60,
    discount: 0,
    finalPrice: 85,
    imageUrl: lisinoprilImg,
    description: "ACE inhibitor used to treat high blood pressure and heart failure.",
  },
  {
    id: 12,
    disease: "Heart",
    name: "Metoprolol",
    genericName: "Metoprolol Tartrate",
    manufacturer: "AstraZeneca",
    category: "Heart",
    price: 90,
    stock: 45,
    discount: 0,
    finalPrice: 90,
    imageUrl: metoprololImg,
    description: "Beta-blocker used to treat high blood pressure and chest pain (angina).",
  },

  // --- NEUROLOGY ---
  {
    id: 13,
    disease: "Neurology",
    name: "Citicoline & Piracetam",
    genericName: "Citicoline + Piracetam",
    manufacturer: "Intas",
    category: "Neurology",
    price: 320,
    stock: 20,
    discount: 15,
    finalPrice: 272,
    imageUrl: citicolineImg,
    description: "Cognitive enhancer used in the treatment of stroke and memory loss.",
  },
  {
    id: 14,
    disease: "Neurology",
    name: "Fluvoxamine",
    genericName: "Fluvoxamine Maleate",
    manufacturer: "Abbott",
    category: "Neurology",
    price: 210,
    stock: 30,
    discount: 0,
    finalPrice: 210,
    imageUrl: fluvoxamineImg,
    description: "SSRI used to treat obsessive-compulsive disorder (OCD) and depression.",
  },
  {
    id: 15,
    disease: "Neurology",
    name: "Neuro-MPG",
    genericName: "Methylcobalamin + Pregabalin",
    manufacturer: "Sun Pharma",
    category: "Neurology",
    price: 180,
    stock: 50,
    discount: 0,
    finalPrice: 180,
    imageUrl: neuroImg,
    description: "Used for neuropathic pain and nerve damage recovery.",
  },

  // --- PAIN RELIEF ---
  {
    id: 16,
    disease: "Pain Relief",
    name: "Acetaminophen",
    genericName: "Paracetamol",
    manufacturer: "GSK",
    category: "Pain Relief",
    price: 30,
    stock: 200,
    discount: 0,
    finalPrice: 30,
    imageUrl: acetaminophenImg,
    description: "Commonly used for mild to moderate pain relief and fever reduction.",
  },
  {
    id: 17,
    disease: "Pain Relief",
    name: "Diclofenac",
    genericName: "Diclofenac Sodium",
    manufacturer: "Novartis",
    category: "Pain Relief",
    price: 55,
    stock: 85,
    discount: 0,
    finalPrice: 55,
    imageUrl: diclofenacImg,
    description: "Relieves pain, swelling, and joint stiffness caused by arthritis.",
  },
  {
    id: 18,
    disease: "Pain Relief",
    name: "Naproxen",
    genericName: "Naproxen Sodium",
    manufacturer: "Sun Pharma",
    category: "Pain Relief",
    price: 90,
    stock: 65,
    discount: 0,
    finalPrice: 90,
    imageUrl: naproxenImg,
    description: "NSAID used to treat pain, menstrual cramps, and inflammatory diseases.",
  },
  {
    id: 19,
    disease: "Pain Relief",
    name: "Tramadol",
    genericName: "Tramadol Hydrochloride",
    manufacturer: "Cipla",
    category: "Pain Relief",
    price: 140,
    stock: 40,
    discount: 0,
    finalPrice: 140,
    imageUrl: tramadolImg,
    description: "Opioid pain medication used to treat moderate to moderately severe pain.",
  },

  // --- RESPIRATORY ---
  {
    id: 20,
    disease: "Respiratory",
    name: "Albuterol",
    genericName: "Salbutamol",
    manufacturer: "Ventolin",
    category: "Respiratory",
    price: 115,
    stock: 90,
    discount: 0,
    finalPrice: 115,
    imageUrl: albuterolImg,
    description: "Quick-relief inhaler for asthma and COPD symptoms.",
  },
  {
    id: 21,
    disease: "Respiratory",
    name: "Budesonide",
    genericName: "Budesonide",
    manufacturer: "Pulmicort",
    category: "Respiratory",
    price: 280,
    stock: 35,
    discount: 10,
    finalPrice: 252,
    imageUrl: budesonideImg,
    description: "Corticosteroid used for long-term management of asthma.",
  },
  {
    id: 22,
    disease: "Respiratory",
    name: "Fluticasone",
    genericName: "Fluticasone Propionate",
    manufacturer: "Glaxo",
    category: "Respiratory",
    price: 340,
    stock: 25,
    discount: 0,
    finalPrice: 340,
    imageUrl: fluticasoneImg,
    description: "Nasal spray for allergic rhinitis and asthma prevention.",
  },
  {
    id: 23,
    disease: "Respiratory",
    name: "Prednisone",
    genericName: "Prednisone",
    manufacturer: "Wysolone",
    category: "Respiratory",
    price: 40,
    stock: 150,
    discount: 0,
    finalPrice: 40,
    imageUrl: prednisoneImg,
    description: "Steroid medication used to suppress the immune system and reduce inflammation.",
  },
  {
    id: 24,
    disease: "Respiratory",
    name: "Albuterol",
    genericName: "Albuterol",
    manufacturer: "Wysolone",
    category: "Respiratory",
    price: 20,
    stock: 150,
    discount: 0,
    finalPrice: 40,
    imageUrl: prednisoneImg,
    description: "Steroid medication used to suppress the immune system and reduce inflammation.",
  },
];

export const STORES: Store[] = [
  {
    id: "1",
    name: "Generic Hub",
    address: "123 Health St, Wellness City",
    isOurStore: true,
    priceInfo: "Best prices guaranteed",
    distance: "0.5 km",
    phone: "(123) 456-7890",
    hours: "Mon-Sat: 9am - 9pm, Sun: 10am - 6pm",
    location: [19.115, 72.869],
  },
  {
    id: "2",
    name: "City Pharmacy",
    address: "456 Main Ave, Metroville",
    isOurStore: false,
    priceInfo: "Avg. 15% more expensive",
    distance: "3.2 km",
    phone: "(123) 555-0101",
    hours: "Mon-Fri: 8am - 10pm, Sat-Sun: 9am - 8pm",
    location: [19.06, 72.83],
  },
];